if ~exist('classifiers_loaded')
    
    classifiers_loaded = 1;

    %% Preset Classifiers
    L2_RLR_PEN_1.train_funct_name = 'train_L2_RLR';
    L2_RLR_PEN_1.test_funct_name  = 'test_L2_RLR';
    L2_RLR_PEN_1.penalty = 1;
    L2_RLR_PEN_5.train_funct_name = 'train_L2_RLR';
    L2_RLR_PEN_5.test_funct_name  = 'test_L2_RLR';
    L2_RLR_PEN_5.penalty = 5;
    L2_RLR_PEN_10.train_funct_name = 'train_L2_RLR';
    L2_RLR_PEN_10.test_funct_name  = 'test_L2_RLR';
    L2_RLR_PEN_10.penalty = 10; 
    L2_RLR_PEN_15.train_funct_name = 'train_L2_RLR';
    L2_RLR_PEN_15.test_funct_name  = 'test_L2_RLR';
    L2_RLR_PEN_15.penalty = 15; 
    L2_RLR_PEN_20.train_funct_name = 'train_L2_RLR';
    L2_RLR_PEN_20.test_funct_name  = 'test_L2_RLR';
    L2_RLR_PEN_20.penalty = 20;
    L2_RLR_PEN_30.train_funct_name = 'train_L2_RLR';
    L2_RLR_PEN_30.test_funct_name  = 'test_L2_RLR';
    L2_RLR_PEN_30.penalty = 30;
    L2_RLR_PEN_100.train_funct_name = 'train_L2_RLR';
    L2_RLR_PEN_100.test_funct_name  = 'test_L2_RLR';
    L2_RLR_PEN_100.penalty = 100; 
    L2_RLR_PEN_50.train_funct_name = 'train_L2_RLR';
    L2_RLR_PEN_50.test_funct_name  = 'test_L2_RLR';
    L2_RLR_PEN_50.penalty = 50; 
    SVM_LINEAR_C1.train_funct_name = 'train_libsvm';
    SVM_LINEAR_C1.test_funct_name = 'test_libsvm';
    SVM_LINEAR_C1.training_options = '-s 0 -t 0 -c 1'; % C-SVC linear kernel cost 1
    SVM_LINEAR_C5.train_funct_name = 'train_libsvm';
    SVM_LINEAR_C5.test_funct_name = 'test_libsvm';
    SVM_LINEAR_C5.training_options = '-s 0 -t 0 -c 5'; % C-SVC linear kernel cost 5
    SVM_POLY_C1.train_funct_name = 'train_libsvm';
    SVM_POLY_C1.test_funct_name = 'test_libsvm';
    SVM_POLY_C1.training_options = '-s 0 -t 1 -c 1'; % C-SVC polynomial kernel cost 1
    SVM_POLY_C5.train_funct_name = 'train_libsvm';
    SVM_POLY_C5.test_funct_name = 'test_libsvm';
    SVM_POLY_C5.training_options = '-s 0 -t 1 -c 5'; % C-SVC polynomial kernel cost 5
    SVM_RBF_C1.train_funct_name = 'train_libsvm';
    SVM_RBF_C1.test_funct_name = 'test_libsvm';
    SVM_RBF_C1.training_options = '-s 0 -t 2 -c 1'; % C-SVC radial basis function kernel cost 1
    SVM_RBF_C5.train_funct_name = 'train_libsvm';
    SVM_RBF_C5.test_funct_name = 'test_libsvm';
    SVM_RBF_C5.training_options = '-s 0 -t 2 -c 5'; % C-SVC radial basis function kernel cost 5
    SVM_SIGMOID_C1.train_funct_name = 'train_libsvm';
    SVM_SIGMOID_C1.test_funct_name = 'test_libsvm';
    SVM_SIGMOID_C1.training_options = '-s 0 -t 3 -c 1'; % C-SVC sigmoid kernel cost 1
    SVM_SIGMOID_C5.train_funct_name = 'train_libsvm';
    SVM_SIGMOID_C5.test_funct_name = 'test_libsvm';
    SVM_SIGMOID_C5.training_options = '-s 0 -t 3 -c 5'; % C-SVC sigmoid kernel cost 5
    SVM_LINEAR_C10.train_funct_name = 'train_libsvm';
    SVM_LINEAR_C10.test_funct_name = 'test_libsvm';
    SVM_LINEAR_C10.training_options = '-s 0 -t 0 -c 10'; % C-SVC linear kernel cost 1
    SVM_LINEAR_C50.train_funct_name = 'train_libsvm';
    SVM_LINEAR_C50.test_funct_name = 'test_libsvm';
    SVM_LINEAR_C50.training_options = '-s 0 -t 0 -c 50'; % C-SVC linear kernel cost 5
    SVM_POLY_C10.train_funct_name = 'train_libsvm';
    SVM_POLY_C10.test_funct_name = 'test_libsvm';
    SVM_POLY_C10.training_options = '-s 0 -t 1 -c 10'; % C-SVC polynomial kernel cost 1
    SVM_POLY_C50.train_funct_name = 'train_libsvm';
    SVM_POLY_C50.test_funct_name = 'test_libsvm';
    SVM_POLY_C50.training_options = '-s 0 -t 1 -c 50'; % C-SVC polynomial kernel cost 5
    SVM_RBF_C10.train_funct_name = 'train_libsvm';
    SVM_RBF_C10.test_funct_name = 'test_libsvm';
    SVM_RBF_C10.training_options = '-s 0 -t 2 -c 10'; % C-SVC radial basis function kernel cost 1
    SVM_RBF_C50.train_funct_name = 'train_libsvm';
    SVM_RBF_C50.test_funct_name = 'test_libsvm';
    SVM_RBF_C50.training_options = '-s 0 -t 2 -c 50'; % C-SVC radial basis function kernel cost 5
    SVM_SIGMOID_C10.train_funct_name = 'train_libsvm';
    SVM_SIGMOID_C10.test_funct_name = 'test_libsvm';
    SVM_SIGMOID_C10.training_options = '-s 0 -t 3 -c 10'; % C-SVC sigmoid kernel cost 1
    SVM_SIGMOID_C50.train_funct_name = 'train_libsvm';
    SVM_SIGMOID_C50.test_funct_name = 'test_libsvm';
    SVM_SIGMOID_C50.training_options = '-s 0 -t 3 -c 50'; % C-SVC sigmoid kernel cost 5
    
    RIDGE_PEN_1.train_funct_name = 'train_ridge';
    RIDGE_PEN_1.test_funct_name = 'test_ridge';
    RIDGE_PEN_1.penalty=1;
    RIDGE_PEN_10.train_funct_name = 'train_ridge';
    RIDGE_PEN_10.test_funct_name = 'test_ridge';
    RIDGE_PEN_10.penalty=10;
    RIDGE_PEN_50.train_funct_name = 'train_ridge';
    RIDGE_PEN_50.test_funct_name = 'test_ridge';
    RIDGE_PEN_50.penalty=50;
    RIDGE_PEN_1000.train_funct_name = 'train_ridge';
    RIDGE_PEN_1000.test_funct_name = 'test_ridge';
    RIDGE_PEN_1000.penalty=1000;
    BP_HIDDEN_10.train_funct_name = 'train_bp_netlab';
    BP_HIDDEN_10.test_funct_name = 'test_bp_netlab';
    BP_HIDDEN_10.nHidden = 10;
    BP_HIDDEN_30.train_funct_name = 'train_bp_netlab';
    BP_HIDDEN_30.test_funct_name = 'test_bp_netlab';
    BP_HIDDEN_30.nHidden = 30;
    ADABOOST_ITER_10.train_funct_name = 'train_adaboost';
    ADABOOST_ITER_10.test_funct_name = 'test_adaboost';
    ADABOOST_ITER_10.numrounds = 10;
    ADABOOST_ITER_50.train_funct_name = 'train_adaboost';
    ADABOOST_ITER_50.test_funct_name = 'test_adaboost';
    ADABOOST_ITER_50.numrounds = 50;
    ADABOOST_ITER_100.train_funct_name = 'train_adaboost';
    ADABOOST_ITER_100.test_funct_name = 'test_adaboost';
    ADABOOST_ITER_100.numrounds = 100;
    RF500.train_funct_name = 'train_random_forest';
    RF500.test_funct_name = 'test_random_forest';
    RF500.nTrees = 500;
    RF1K.train_funct_name = 'train_random_forest';
    RF1K.test_funct_name = 'test_random_forest';
    RF1K.nTrees = 1000;
    ADA500.train_funct_name = 'train_ensemble';
    ADA500.test_funct_name = 'test_ensemble';
    ADA500.method = 'AdaBoostM1';
    ADA500.nTrees = 500;
    ADA1K.train_funct_name = 'train_ensemble';
    ADA1K.test_funct_name = 'test_ensemble';
    ADA1K.method = 'AdaBoostM1';
    ADA1K.nTrees = 1000;
    
    LOGIT500.train_funct_name = 'train_ensemble';
    LOGIT500.test_funct_name = 'test_ensemble';
    LOGIT500.method = 'LogitBoost';
    LOGIT500.nTrees = 500;
    LOGIT1K.train_funct_name = 'train_ensemble';
    LOGIT1K.test_funct_name = 'test_ensemble';
    LOGIT1K.method = 'LogitBoost';
    LOGIT1K.nTrees = 1000;
    
    RBST500.train_funct_name = 'train_ensemble';
    RBST500.test_funct_name = 'test_ensemble';
    RBST500.method = 'RobustBoost';
    RBST500.nTrees = 500;
    RBST1K.train_funct_name = 'train_ensemble';
    RBST1K.test_funct_name = 'test_ensemble';
    RBST1K.method = 'RobustBoost';
    RBST1K.nTrees = 1000;
    
    classifiers{1} = L2_RLR_PEN_1;
    classifiers{2} = L2_RLR_PEN_5;
    classifiers{3} = L2_RLR_PEN_10;
    classifiers{4} = L2_RLR_PEN_15;
    classifiers{5} = L2_RLR_PEN_20;
    classifiers{6} = L2_RLR_PEN_30;
    classifiers{7} = L2_RLR_PEN_50;
    classifiers{8} = L2_RLR_PEN_100;

    classifiers{9} = SVM_LINEAR_C1;
    classifiers{10} = SVM_LINEAR_C5;
    classifiers{11} = SVM_LINEAR_C10;
    classifiers{12} = SVM_LINEAR_C50;
    
    classifiers{13} = SVM_POLY_C1;
    classifiers{14} = SVM_POLY_C5;
    classifiers{15} = SVM_POLY_C10;
    classifiers{16} = SVM_POLY_C50;
    
    classifiers{17} = SVM_RBF_C1;
    classifiers{18} = SVM_RBF_C5;
    classifiers{19} = SVM_RBF_C10;
    classifiers{20} = SVM_RBF_C50;
    
    classifiers{21} = SVM_SIGMOID_C1;
    classifiers{22} = SVM_SIGMOID_C5;
    classifiers{23} = SVM_SIGMOID_C10;
    classifiers{24} = SVM_SIGMOID_C50;
    
    classifiers{25} = BP_HIDDEN_10;
    classifiers{26} = BP_HIDDEN_30;
    
    classifiers{27} = RF500;
    classifiers{28} = RF1K;
    classifiers{29} = ADA500;
    classifiers{30} = ADA1K;
    
    classifiers{31} = ADABOOST_ITER_10;
    classifiers{32} = ADABOOST_ITER_50;
    classifiers{33} = LOGIT500;
    classifiers{34} = LOGIT1K;
    classifiers{35} = RBST500;
    classifiers{36} = RBST1K;
end