function makeFig_bar_4mdp(Y1, E1)
%CREATEFIGURE(Y1, E1)
%  Y1:  errorbar y
%  E1:  errorbar e

%  Auto-generated by MATLAB on 28-Oct-2015 21:27:45

% Create figure
figure1 = figure('Color',[1 1 1], 'Position',[100, 100, 800, 600]);

% Create axes
axes1 = axes('Parent',figure1,'XTickLabel',{'No Rev','Rev','No Rev','Rev'},...
    'XTick',[1 2 3 4],...
    'FontSize',15);
box(axes1,'on');
hold(axes1,'all');

% Create errorbar
errorbar(Y1,E1,'MarkerSize',10,'MarkerFaceColor',[0 0 0],'Marker','o',...
    'LineStyle','none',...
    'LineWidth',5,...
    'Color',[0 0 0]);

% Create title
title('Mean S2 X S1 replay','FontSize',15);

% Create xlabel
xlabel('No Noise                                 Noise','FontSize',15);

