classifier_names = {'Logistic Regression',...
    'Logistic Regression',...
    'Logistic Regression',...
    'Logistic Regression',...
    'Logistic Regression',...
    'Logistic Regression',...
    'Logistic Regression',...
    'Logistic Regression',...
    'SVM',...
    'SVM',...
    'SVM',...
    'SVM',...
    'SVM',...
    'SVM',...
    'SVM',...
    'SVM',...
    'SVM',...
    'SVM',...
    'SVM',...
    'SVM',...
    'SVM',...
    'SVM',...
    'SVM',...
    'SVM',...
    'Back Propagation',...
    'Back Propagation',...
    'Random Forest',...
    'Random Forest',...
    'Adaboost',...
    'Adaboost'};
classifier_params = {'Penalty = 1',...
'Penalty = 5',...
'Penalty = 10',...
'Penalty = 15',...
'Penalty = 20',...
'Penalty = 30',...
'Penalty = 50',...
'Penalty = 100',...
'Penality = 1',...
'Penality = 5',...
'Penality = 10',...
'Penality = 50',...
'Penality = 1',...
'Penality = 5',...
'Penality = 10',...
'Penality = 50',...
'Penality = 1',...
'Penality = 5',...
'Penality = 10',...
'Penality = 50',...
'Penality = 1',...
'Penality = 5',...
'Penality = 10',...
'Penality = 50',...
'Hidden = 10',...
'Hidden = 30',...
'Trees = 500',...
'Trees = 1K',...
'Trees = 500',...
'Trees = 1K'};
classifier_colors = {[1 0 0],...
[1 0 0],...
[1 0 0],...
[1 0 0],...
[1 0 0],...
[1 0 0],...
[1 0 0],...
[1 0 0],...
[0 1 0],...
[0 1 0],...
[0 1 0],...
[0 1 0],...
[0 0 1],...
[0 0 1],...
[0 0 1],...
[0 0 1],...
[0.8 0.8 0],...
[1 1 0],...
[1 1 0],...
[1 1 0],...
[1 0 1],...
[1 0 1],...
[1 0 1],...
[1 0 1],...
[0 1 1],...
[0 1 1],...
[0.5 0.5 0.5],...
[0.5 0.5 0.5],...
[0 0.5 0.5],...
[0 0.5 0.5]};

VALID_SUBJECTS = [1:9 11:23 25:26];
for s = 1:26
    if s ==10 || s == 24
        continue;
    end
    disp(s);
    load(sprintf('MVPA_xval/loc1/subject%d_classifier_xval.mat',s),'classifier_performance');
    for i = 1:30
        clsmean(find(VALID_SUBJECTS==s),i) = mean(classifier_performance(i,:));
    end
end
figure;
hold on;
subjectMean = mean(clsmean);
stdev = std(clsmean);
b = bar(1:8, subjectMean(1:8), 'FaceColor', classifier_colors{1}, 'EdgeColor','none');
b = bar(9:12, subjectMean(9:12), 'FaceColor', classifier_colors{9}, 'EdgeColor','none');
b = bar(13:16, subjectMean(13:16), 'FaceColor', classifier_colors{13}, 'EdgeColor','none');
b = bar(17:20, subjectMean(17:20), 'FaceColor', classifier_colors{17}, 'EdgeColor','none');
b = bar(21:24, subjectMean(21:24), 'FaceColor', classifier_colors{21}, 'EdgeColor','none');
b = bar(25:26, subjectMean(25:26), 'FaceColor', classifier_colors{25}, 'EdgeColor','none');
b = bar(27:28, subjectMean(27:28), 'FaceColor', classifier_colors{27}, 'EdgeColor','none');
b = bar(29:30, subjectMean(29:30), 'FaceColor', classifier_colors{29}, 'EdgeColor','none');
h = errorbar(1:30, subjectMean(1:30), stdev(1:30));
set(h,'Color',[0.5 0.5 0.5]);
set(h,'LineStyle','none');
xlabel('Classifier Parameters','Fontsize',14, 'FontWeight','bold')
ylabel('Accuracy','Fontsize',14, 'FontWeight','bold');
legend('Logistic Regression','SVM-Linear','SVM-Poly','SVM-RBF','SVM-Sigmoid','Back Propagation','Random Forest','Adaboost')
title('Localizer 1 Cross-Validation for Face and Scene','Fontsize',14, 'FontWeight','bold');
axis([0 31 0 1]);
xticklabel_rotate(1:30,45,classifier_params,'Fontsize', 10, 'FontWeight', 'bold');

VALID_SUBJECTS = [5:9 11:23 25:26];
for s = 5:26
    if s ==10 || s == 24
        continue;
    end
    disp(s);
    load(sprintf('MVPA_xval/loc2/subject%d_classifier_xval.mat',s),'classifier_performance');
    for i = 1:30
        clsmean2(find(VALID_SUBJECTS==s),i) = mean(classifier_performance(i,:));
    end
end

figure;
hold on;
subjectMean = mean(clsmean2);
stdev = std(clsmean2);
b = bar(1:8, subjectMean(1:8), 'FaceColor', classifier_colors{1}, 'EdgeColor','none');
b = bar(9:12, subjectMean(9:12), 'FaceColor', classifier_colors{9}, 'EdgeColor','none');
b = bar(13:16, subjectMean(13:16), 'FaceColor', classifier_colors{13}, 'EdgeColor','none');
b = bar(17:20, subjectMean(17:20), 'FaceColor', classifier_colors{17}, 'EdgeColor','none');
b = bar(21:24, subjectMean(21:24), 'FaceColor', classifier_colors{21}, 'EdgeColor','none');
b = bar(25:26, subjectMean(25:26), 'FaceColor', classifier_colors{25}, 'EdgeColor','none');
b = bar(27:28, subjectMean(27:28), 'FaceColor', classifier_colors{27}, 'EdgeColor','none');
b = bar(29:30, subjectMean(29:30), 'FaceColor', classifier_colors{29}, 'EdgeColor','none');
h = errorbar(1:30, subjectMean(1:30), stdev(1:30));
set(h,'Color',[0.5 0.5 0.5]);
set(h,'LineStyle','none');
xlabel('Classifier Parameters','Fontsize',14, 'FontWeight','bold')
ylabel('Accuracy','Fontsize',14, 'FontWeight','bold');
legend('Logistic Regression','SVM-Linear','SVM-Poly','SVM-RBF','SVM-Sigmoid','Back Propagation','Random Forest','Adaboost')
title('Localizer 2 Cross-Validation for Face and Scene','Fontsize',14, 'FontWeight','bold');
axis([0 31 0 1]);
xticklabel_rotate(1:30,45,classifier_params,'Fontsize', 10, 'FontWeight', 'bold');